<?php

function vals_soc_menu(){
	
    $items['admin/config/vals_soc'] = array(
		'title' => 'VALS Summer of code',
		'type' => MENU_NORMAL_ITEM,
    	'page callback' => 'vals_soc_timeline_admin_overview_page',
		'access arguments' => array('access administration pages'),
    	'description' => 'Allow Administration on the summer of code module',
    	'file' => 'vals_soc.pages.inc',
    	'file path' => drupal_get_path('module', 'vals_soc') . '/includes/',
    );

    $items['admin/config/vals_soc/program_settings'] = array(
    	'title' => 'Program Settings',
    	'type' => MENU_NORMAL_ITEM,
    	'page callback' => 'vals_soc_timeline_admin_program_page',
    	'access arguments' => array('access administration pages'),
    	'description' => 'Allow Administration on the summer of code module',
    	'file' => 'vals_soc.pages.inc',
    	'file path' => drupal_get_path('module', 'vals_soc') . '/includes/',
    );
    
    $items['admin/config/vals_soc/program_settings/timeline'] = array(
    	'title' => 'Edit Timeline',
    	'type' => MENU_NORMAL_ITEM,
    	'page callback' => 'drupal_get_form',
    	'page arguments' => array('vals_soc_admin_timeline_form'),
    	'access arguments' => array('access administration pages'),
    	'description' => 'Edit the timeline and other settings.',
    	'file' => 'vals_soc.forms.inc',
    	'file path' => drupal_get_path('module', 'vals_soc') . '/includes/',
    );
    
	$items['admin/config/vals_soc/program_settings/messages'] = array(
		'title' => 'Edit Messages',
    	'type' => MENU_NORMAL_ITEM,
    	'page callback' => 'drupal_get_form',
    	'page arguments' => array('vals_soc_admin_messages_form'),
    	'access arguments' => array('access administration pages'),
    	'description' => 'Edit the email messages that are sent to users.',
    	'file' => 'vals_soc.forms.inc',
    	'file path' => drupal_get_path('module', 'vals_soc') . '/includes/',
    );

    return $items;
}

function vals_soc_mail_alter(&$message) {
	$headers = array(
			'MIME-Version' => '1.0',
			'Content-Type' => 'text/html; charset=iso-8859-1; format=flowed',
			'Content-Transfer-Encoding' => '8Bit',
			'X-Mailer' => 'Drupal',
	);
	foreach ($headers as $key => $value) {
		$message['headers'][$key] = $value;
	}
}

function vals_soc_mail($key, &$message, $params) {

	switch($key) {
		case 'vals_soc_email_accepted_organization':
			$message['subject'] = t('Organization application for VALS summer of code');
			$message['body'][] = variable_get('vals_accepted_organizations_message')['value'];
			if (isset($params['headers']) && is_array($params['headers'])) {
				$message['headers'] += $params['headers'];
			}
			break;

		case 'vals_soc_email_rejected_organization':
			$message['subject'] = t('Organization application for VALS summer of code');
			$message['body'][] = variable_get('vals_rejected_organizations_message')['value'];
			break;

		case 'vals_soc_email_mentor_welcome':
			$message['subject'] = t('Welcome mentor to the VALS summer of code');
			$message['body'][] = variable_get('vals_mentor_welcome_message')['value'];
			break;
				
		case 'vals_soc_email_student_welcome':
			$message['subject'] = t('Welcome student to the VALS summer of code');
			$message['body'][] = variable_get('vals_student_welcome_message')['value'];
			break;
				
		case 'vals_soc_accepted_students':
			$message['subject'] = t('Your project proposal to the VALS summer of code');
			$message['body'][] = variable_get('vals_accepted_students_message')['value'];
			break;

		case 'vals_soc_rejected_students':
			$message['subject'] = t('Your project proposal to the VALS summer of code');
			$message['body'][] = variable_get('vals_rejected_students_message')['value'];
			break;
	}
}

/**
 * Implements hook_help().
 */
function vals_soc_help($path, $arg) {
	//TODO
}
