<h2 id="title-section-how-it-works">How VALS Summer of Code Works</h2>
<ol id="list-how-it-works">
	<li id="how-it-works-item1" class="first">
		<strong>
			Propose a project
			<span>for approval by a mentoring open source organisation</span>
		</strong>
	</li>
	<li id="how-it-works-item2" class="second">
		<strong>Code the summer away</strong>
	</li>
	<li id="how-it-works-item3" class="third">
		<strong>
			Achieve Ultimate Glory
			<span>(and get a nice paycheck)</span>
		</strong>
	</li>
</ol>
<div id="block-how-it-works-description" class="description">
<p>VALS Summer of Code is a global program that offers students stipends to write code for open source projects. 
We have worked with the open source community to identify and fund exciting projects for the upcoming summer.</p>
</div>
